###
# Main server configuration
###
name: "Concentrator"
host: 0.0.0.0
port: 2003


###
# How we want to relay requests.
###
relay_method:  consistent_hashing

###
# Backend carbon or statsd servers.
# Carbon is typically 2003. Statsd 8125
###
backends:
 - 127.0.0.1: 2003
 #- 127.0.0.1: 8127
 #- server2:   8125

